name: test pytorch

on:
  push:
    paths:
      - 'jupyter/pytorch/ubi9-python-3.9/*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
              make jupyter-pytorch-ubi9-python-3.9

      - name: Run test_notebook.ipynb
        run: |
          echo "nothing yet"
